version: "3"

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app1
    command: sh -c "uvicorn distributed_python_server:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8001:8000"

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app2
    command: sh -c "uvicorn distributed_python_server:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8002:8000"

  app3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app3
    command: sh -c "uvicorn distributed_python_server:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8003:8000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
